Develop
Obote/Awsome-book pull request #1
Opened 2022-08-02 18:02 UTC by Obote

### **What does this PR do?**

- Create a collection that keeps a list of books (hint: you can use an array of objects for that).
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection.
- Display all books saved in the collection in the top part of the page.
- Make sure that when a user clicks the "Add" button.
- Make sure that when a user clicks the "Remove" button
- Make sure that data is preserved in the browser's memory by using localStorage.

2022-08-02 18:04 UTC, leonardodiasb requested changes
# INVALID ❌ ❌ ❌ 

Hi @Obote, 👋

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request ❌
 - You have submitted a Pull Request that has linter issues. Kindly check and fix all your linters before submitting a Pull Request.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

✅ Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_⚠️ Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

----
_Invalid Code Review Request does not count into the code reviews limit._

2022-08-02 19:21 UTC, VICTOR-CHUKWU requested changes
Hi @Obote  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-02 19:21 UTC, VICTOR-CHUKWU commented on JS/index.js
> +};
- [ ] on refresh of your page, an empty book is added, this is because function `addTitleAuthor` is being called on every render of the page and the function calls `createBook`, kindly fix this
 
![Screenshot from 2022-08-02 20-13-06](https://user-images.githubusercontent.com/66097371/182456028-3b0e53f3-29ed-48ab-8316-477d5d9f3bf5.png)

2022-08-03 13:07 UTC, vechicin approved these changes
# Hi @Obote and @DhuruvSingh ✋, 

Your project is complete! 🎯 🧠 💯 
There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights ⚡ 

- [x] Good job fixing the bug noted by the previous reviewer.

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 13:07 UTC, vechicin commented on JS/index.js
> +    books.push(book);
[OPTIONAL] Consider using methods that don't mutate the array.

<img width="960" alt="Screen Shot 2022-08-03 at 8 04 46" src="https://user-images.githubusercontent.com/82426682/182614904-c7a31800-fe6e-4a57-b7ef-fb0db4b7a6a1.png">

2022-08-03 13:07 UTC, vechicin commented on JS/index.js
> +        newBooks.splice(index, 1);
[OPTIONAL] Consider using methods that don't mutate the array.

<img width="959" alt="Screen Shot 2022-08-03 at 8 05 38" src="https://user-images.githubusercontent.com/82426682/182615050-57bfa3f6-cbc4-4221-ae9e-16d7eeaa3150.png">

2022-08-03 13:15 UTC, merged