Refactor with classes
Obote/Awsome-book pull request #2
Opened 2022-08-03 18:20 UTC by Obote

### **What does this repo do?**

- Use JavaScript classes instead of objects and arrays.
- Create class methods to add and remove books.
- Maintain all of the original functionality of the application (i.e. no bugs were introduced while refactoring).
- Don't use any library or framework, use only plain JavaScript.
- Add CSS styles to the application to make it match this wireframe.
- You can use the styles of your choice (colors, fonts, backgrounds, etc.), but try to follow the general layout.

2022-08-03 18:53 UTC, DammyShittu requested changes
Hi team,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Use of classes

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-03 18:53 UTC, DammyShittu commented on JS/index.js
> +    this.saveToLocalStorage();
- [ ] There seems to be a bug in your app. When I add two books of the title and author and delete only one, both books are deleted from the local storage (even though the other book remains on the page), but that should not be. Only the deleted book should be removed from the local storage. You can fix this by deleting books using unique ids

  Duplicate books are added | One book is deleted, and both books are removed from local storage | Page is refreshed, the other book disappears
  :---:|:---:|:---:
  ![auth-1](https://user-images.githubusercontent.com/54848363/182686166-c5cf124e-31e5-4803-964f-bc40041c281f.jpg) | ![auth-2](https://user-images.githubusercontent.com/54848363/182686163-99bde490-a7af-4c9a-a2ea-6010ef1fabf9.jpg) | ![auth-3](https://user-images.githubusercontent.com/54848363/182686161-29dc43e3-8687-4e2c-87e5-200aea99abd7.jpg)

2022-08-04 15:32 UTC, danmainah requested changes
Hi @Obote and @DhuruvSingh , 

Great work on making the changes requested by a previous reviewer 👏  👏 👏
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


 ## Highlights
✔️ No linter errors
✔️ Github flow was correctly used
✔️  Good design


 # Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-04 15:32 UTC, danmainah commented on JS/index.js
> +  static removeBook(elem) {
- [ ] @Obote and @DhuruvSingh great work trying to fix the error, however, when I delete a book the changes made are not implemented in the local storage.Kindly check on it.

2022-08-04 19:49 UTC, Obote commented on JS/index.js
> +  static removeBook(elem) {
Hello, @danmainah I have been looking at this for a while now but seems I can`t figure out what you're asking for.

2022-08-05 06:34 UTC, HAMMAS-SALEEM approved these changes
# Status: Approved :green_circle:
![success](https://camo.githubusercontent.com/6ada59f6189497c1c2cae6d06f8154b7307a58643f232340e288140ed469eb28/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f6c3366516333614356304871707a5763552f67697068792e676966)

## Hey @Obote, @DhuruvSingh  :wave:

Great work on implementing the changes requested by the previous reviewer. Your project is complete. :blush:
There is nothing else to say about your project. :+1:

## Highlights :1st_place_medal:
:heavy_check_mark: Followed Linters
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Following the requirements

### [Optional]

_All the changes with optional tags are not crucial enough to prevent you from getting the approval but we highly recommend to students that they should take these changes into consideration._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

---------------------------------------

_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-05 06:40 UTC, merged